SET IDENTITY_INSERT GL_C_PARAMETRO ON 
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (1,0,-1,'Sel','Seleccione...',0,1,'7/28/2016','12/19/2020','jenita')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (10,3,2,'','Player',0,1,'8/15/2018','','JACASHIRA')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (11,4,0,'','Formato exportación',0,1,'5/18/2017','10/1/2018','CGAYOSSO')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (12,4,1,'','PDF',0,1,'5/18/2017','','CGAYOSSO')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (13,4,2,'','Excel',0,1,'5/18/2017','','CGAYOSSO')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (14,5,0,'','Tipo Canal',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (15,5,1,'','Video',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (16,5,2,'','Imagen',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (17,5,3,'','Mensaje',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (18,5,4,'','Transmisión',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (19,5,5,'','Audio',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (2,1,0,'','Estatus',0,1,'7/28/2016','11/3/2016','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (20,6,0,'','Tipo contenido',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (21,6,1,'','Video',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (22,6,2,'','Imagen',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (23,6,3,'','Mensaje',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (24,6,4,'','Audio',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (25,6,5,'','Transmisión',0,1,'8/22/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (26,7,0,'','Tipo mensaje',0,1,'8/18/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (27,7,1,'','Cintilla',0,8,'8/18/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (28,7,2,'','Telon',0,9,'8/18/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (29,7,3,'','Fijo',0,10,'8/18/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (3,1,1,'AC','Activo',0,1,'7/28/2016','8/15/2017','ESPINOZA')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (30,8,0,'','Mensaje cintilla',0,1,'8/21/2018','10/1/2018','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (31,8,1,'','Izquierda',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (32,8,2,'','Derecha',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (33,9,0,'','Mensaje telon',0,1,'8/21/2018','10/1/2018','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (34,9,1,'','Baja',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (35,9,2,'','Sube',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (36,10,0,'','Mensaje fijo',0,1,'8/21/2018','10/1/2018','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (37,10,1,'','Fija',0,1,'8/21/2018','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (38,11,0,'','Género',0,1,'7/29/2016','11/3/2016','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (39,11,1,'M','Masculino',0,1,'7/29/2016','10/1/2018','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (4,1,2,'INAC','Inactivo',0,1,'8/1/2016','12/17/2020','ADMIN')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (40,11,2,'F','Femenino',0,1,'7/29/2016','10/1/2018','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (41,12,0,'','Tipo de dato',0,1,'7/2/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (42,12,1,'INT','Eentero',0,1,'7/2/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (43,12,2,'VCHAR','Cadena de texto',0,1,'7/2/2019','','FANGELE')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (44,12,3,'IMG','Imagen',0,1,'7/2/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (45,13,0,'','Tipo rostro',0,1,'9/3/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (46,13,1,'','Ovalado',0,0,'9/3/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (47,13,2,'','Alargado',0,0,'9/3/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (48,13,3,'','Redondo',0,0,'9/3/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (49,14,0,'','Resolución',0,1,'9/6/2019','9/6/2019','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (5,2,0,'','Tipo dirección',0,1,'7/29/2016','2/4/2020','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (50,14,1,'','1920X1080',0,0,'9/6/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (51,14,2,'','1600X900',0,1,'9/6/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (52,14,3,'','1366x768',0,0,'9/6/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (53,14,4,'','1360x768',0,0,'9/6/2019','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (54,2,3,'','Personal',0,0,'1/16/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (56,14,5,'','1280x768',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (57,14,6,'','1280x720',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (58,14,7,'','1280x600',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (59,14,8,'','1024x768',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (6,2,1,'','Fiscal',0,1,'7/29/2016','11/3/2016','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (60,14,9,'','800x600',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (61,14,10,'','1660X900',0,0,'6/23/2020','','FANGELES')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (7,2,2,'','Correspondencia',0,1,'8/1/2016','11/3/2016','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (8,3,0,'','Tipo dispositivo',0,1,'10/17/2016','11/3/2016','FCRUZ')
INSERT INTO GL_C_PARAMETRO(ID_PARAMETRO,PARAMETRO,CONSECUTIVO,CLAVE,DESCRIPCION,PREDETERMINADO,FACTOR,FEC_ALTA,FEC_MOD,USUARIO)VALUES (9,3,1,'','Sagen',0,1,'4/19/2017','','ADMIN')
SET IDENTITY_INSERT GL_C_PARAMETRO OFF
UPDATE GL_C_PARAMETRO SET PARAMETRO = 0,CONSECUTIVO = -1,CLAVE = 'Sel',DESCRIPCION = 'Seleccione...',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/28/2016',FEC_MOD = '12/19/2020',USUARIO = 'jenita'WHERE ID_PARAMETRO = 1
UPDATE GL_C_PARAMETRO SET PARAMETRO = 1,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Estatus',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/28/2016',FEC_MOD = '11/3/2016',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 2
UPDATE GL_C_PARAMETRO SET PARAMETRO = 1,CONSECUTIVO = 1,CLAVE = 'AC',DESCRIPCION = 'Activo',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/28/2016',FEC_MOD = '8/15/2017',USUARIO = 'ESPINOZA'WHERE ID_PARAMETRO = 3
UPDATE GL_C_PARAMETRO SET PARAMETRO = 1,CONSECUTIVO = 2,CLAVE = 'INAC',DESCRIPCION = 'Inactivo',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/1/2016',FEC_MOD = '12/17/2020',USUARIO = 'ADMIN'WHERE ID_PARAMETRO = 4
UPDATE GL_C_PARAMETRO SET PARAMETRO = 10,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Mensaje fijo',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '10/1/2018',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 36
UPDATE GL_C_PARAMETRO SET PARAMETRO = 10,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Fija',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 37
UPDATE GL_C_PARAMETRO SET PARAMETRO = 11,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Género',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/29/2016',FEC_MOD = '11/3/2016',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 38
UPDATE GL_C_PARAMETRO SET PARAMETRO = 11,CONSECUTIVO = 1,CLAVE = 'M',DESCRIPCION = 'Masculino',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/29/2016',FEC_MOD = '10/1/2018',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 39
UPDATE GL_C_PARAMETRO SET PARAMETRO = 11,CONSECUTIVO = 2,CLAVE = 'F',DESCRIPCION = 'Femenino',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/29/2016',FEC_MOD = '10/1/2018',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 40
UPDATE GL_C_PARAMETRO SET PARAMETRO = 12,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo de dato',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/2/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 41
UPDATE GL_C_PARAMETRO SET PARAMETRO = 12,CONSECUTIVO = 1,CLAVE = 'INT',DESCRIPCION = 'Eentero',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/2/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 42
UPDATE GL_C_PARAMETRO SET PARAMETRO = 12,CONSECUTIVO = 2,CLAVE = 'VCHAR',DESCRIPCION = 'Cadena de texto',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/2/2019',FEC_MOD = '',USUARIO = 'FANGELE'WHERE ID_PARAMETRO = 43
UPDATE GL_C_PARAMETRO SET PARAMETRO = 12,CONSECUTIVO = 3,CLAVE = 'IMG',DESCRIPCION = 'Imagen',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/2/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 44
UPDATE GL_C_PARAMETRO SET PARAMETRO = 13,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo rostro',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '9/3/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 45
UPDATE GL_C_PARAMETRO SET PARAMETRO = 13,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Ovalado',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/3/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 46
UPDATE GL_C_PARAMETRO SET PARAMETRO = 13,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Alargado',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/3/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 47
UPDATE GL_C_PARAMETRO SET PARAMETRO = 13,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = 'Redondo',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/3/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 48
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Resolución',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '9/6/2019',FEC_MOD = '9/6/2019',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 49
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = '1920X1080',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/6/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 50
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 10,CLAVE = '',DESCRIPCION = '1660X900',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 61
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = '1600X900',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '9/6/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 51
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = '1366x768',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/6/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 52
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 4,CLAVE = '',DESCRIPCION = '1360x768',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '9/6/2019',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 53
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 5,CLAVE = '',DESCRIPCION = '1280x768',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 56
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 6,CLAVE = '',DESCRIPCION = '1280x720',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 57
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 7,CLAVE = '',DESCRIPCION = '1280x600',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 58
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 8,CLAVE = '',DESCRIPCION = '1024x768',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 59
UPDATE GL_C_PARAMETRO SET PARAMETRO = 14,CONSECUTIVO = 9,CLAVE = '',DESCRIPCION = '800x600',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '6/23/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 60
UPDATE GL_C_PARAMETRO SET PARAMETRO = 2,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo dirección',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/29/2016',FEC_MOD = '2/4/2020',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 5
UPDATE GL_C_PARAMETRO SET PARAMETRO = 2,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Fiscal',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '7/29/2016',FEC_MOD = '11/3/2016',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 6
UPDATE GL_C_PARAMETRO SET PARAMETRO = 2,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Correspondencia',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/1/2016',FEC_MOD = '11/3/2016',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 7
UPDATE GL_C_PARAMETRO SET PARAMETRO = 2,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = 'Personal',PREDETERMINADO = 0,FACTOR = 0,FEC_ALTA = '1/16/2020',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 54
UPDATE GL_C_PARAMETRO SET PARAMETRO = 3,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo dispositivo',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '10/17/2016',FEC_MOD = '11/3/2016',USUARIO = 'FCRUZ'WHERE ID_PARAMETRO = 8
UPDATE GL_C_PARAMETRO SET PARAMETRO = 3,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Sagen',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '4/19/2017',FEC_MOD = '',USUARIO = 'ADMIN'WHERE ID_PARAMETRO = 9
UPDATE GL_C_PARAMETRO SET PARAMETRO = 3,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Player',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/15/2018',FEC_MOD = '',USUARIO = 'JACASHIRA'WHERE ID_PARAMETRO = 10
UPDATE GL_C_PARAMETRO SET PARAMETRO = 4,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Formato exportación',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '5/18/2017',FEC_MOD = '10/1/2018',USUARIO = 'CGAYOSSO'WHERE ID_PARAMETRO = 11
UPDATE GL_C_PARAMETRO SET PARAMETRO = 4,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'PDF',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '5/18/2017',FEC_MOD = '',USUARIO = 'CGAYOSSO'WHERE ID_PARAMETRO = 12
UPDATE GL_C_PARAMETRO SET PARAMETRO = 4,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Excel',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '5/18/2017',FEC_MOD = '',USUARIO = 'CGAYOSSO'WHERE ID_PARAMETRO = 13
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo Canal',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 14
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Video',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 15
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Imagen',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 16
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = 'Mensaje',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 17
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 4,CLAVE = '',DESCRIPCION = 'Transmisión',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 18
UPDATE GL_C_PARAMETRO SET PARAMETRO = 5,CONSECUTIVO = 5,CLAVE = '',DESCRIPCION = 'Audio',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 19
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo contenido',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 20
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Video',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 21
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Imagen',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 22
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = 'Mensaje',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 23
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 4,CLAVE = '',DESCRIPCION = 'Audio',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 24
UPDATE GL_C_PARAMETRO SET PARAMETRO = 6,CONSECUTIVO = 5,CLAVE = '',DESCRIPCION = 'Transmisión',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/22/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 25
UPDATE GL_C_PARAMETRO SET PARAMETRO = 7,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Tipo mensaje',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/18/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 26
UPDATE GL_C_PARAMETRO SET PARAMETRO = 7,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Cintilla',PREDETERMINADO = 0,FACTOR = 8,FEC_ALTA = '8/18/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 27
UPDATE GL_C_PARAMETRO SET PARAMETRO = 7,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Telon',PREDETERMINADO = 0,FACTOR = 9,FEC_ALTA = '8/18/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 28
UPDATE GL_C_PARAMETRO SET PARAMETRO = 7,CONSECUTIVO = 3,CLAVE = '',DESCRIPCION = 'Fijo',PREDETERMINADO = 0,FACTOR = 10,FEC_ALTA = '8/18/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 29
UPDATE GL_C_PARAMETRO SET PARAMETRO = 8,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Mensaje cintilla',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '10/1/2018',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 30
UPDATE GL_C_PARAMETRO SET PARAMETRO = 8,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Izquierda',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 31
UPDATE GL_C_PARAMETRO SET PARAMETRO = 8,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Derecha',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 32
UPDATE GL_C_PARAMETRO SET PARAMETRO = 9,CONSECUTIVO = 0,CLAVE = '',DESCRIPCION = 'Mensaje telon',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '10/1/2018',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 33
UPDATE GL_C_PARAMETRO SET PARAMETRO = 9,CONSECUTIVO = 1,CLAVE = '',DESCRIPCION = 'Baja',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 34
UPDATE GL_C_PARAMETRO SET PARAMETRO = 9,CONSECUTIVO = 2,CLAVE = '',DESCRIPCION = 'Sube',PREDETERMINADO = 0,FACTOR = 1,FEC_ALTA = '8/21/2018',FEC_MOD = '',USUARIO = 'FANGELES'WHERE ID_PARAMETRO = 35


SELECT * FROM GL_C_PARAMETRO
