
SELECT * FROM GL_D_LICENCIA_ACTIVA

truncate table GL_D_LICENCIA_ACTIVA
UPDATE GL_D_LICENCIA_ACTIVA SET ID_ESTATUS = 3 

SELECT * FROM TV_C_REPOSITORIO ORDER BY FEC_ALTA DESC


UPDATE TV_C_REPRODUCTOR SET RELOJ = 1 WHERE ID_REPRODUCTOR = 2001

SELECT * FROM GL_D_LICENCIA_ACTIVA
  
TRUNCATE TABLE GL_D_LICENCIA_ACTIVA



SELECT * FROM TV_D_REPOSITORIO

SELECT * FROM TV_C_REPRODUCTOR


	SELECT r.*, tr.*, t.* FROM 
	TV_C_REPRODUCTOR r
	LEFT JOIN TV_R_TEMPLATE_REPRODUCTOR tr
	ON r.ID_REPRODUCTOR = tr.ID_REPRODUCTOR
	LEFT JOIN TV_D_TEMPLATES t
	ON tr.ID_TEMPLATE = t.ID_TEMPLATE 
  WHERE(
     r.DESCRIPCION LIKE CASE WHEN '0' = '0' THEN r.DESCRIPCION ELSE '%' + '0' +'%' END)
   ORDER BY r.ID_REPRODUCTOR DESC
	OFFSET ((1-1) * 10) ROWS
  FETCH NEXT 10 ROWS ONLY 


  SELECT * FROM TV_R_TEMPLATE_REPRODUCTOR
  SELECT * FROM TV_C_REPRODUCTOR
  SELECT * FROM TV_D_TEMPLATES

  DELETE FROM TV_R_TEMPLATE_REPRODUCTOR WHERE ID_TEMPLATE = 0



  SELECT * FROM TV_D_CANAL
  SELECT * FROM TV_R_CANAL_CONTENIDO 
  SELECT * FROM TV_C_REPOSITORIO

  SELECT * FROM GL_D_LICENCIA_ACTIVA
  UPDATE GL_D_LICENCIA_ACTIVA SET ID_ESTATUS = 3 WHERE ID_LICENCIA_ACTIVA = 1

  TRUNCATE TABLE TV_C_REPOSITORIO