CREATE PROCEDURE [dbo].[SPD_TV_C_REPOSITORIO]
    @ID_REPOSITORIO INT
    ,@NOMBRE NVARCHAR(150)
AS
BEGIN
  SET NOCOUNT ON
  DELETE FROM TV_C_REPOSITORIO
    WHERE
      ID_REPOSITORIO = @ID_REPOSITORIO
      OR NOMBRE = @NOMBRE 
  SET NOCOUNT OFF
END