-- =============================================
-- Author:		Ing. Luis FErnando Angeles Escamilla
-- Create date: 15-09-2020
-- Description:	Creacion de tablas dinamicas
-- =============================================
CREATE PROCEDURE [dbo].[SPI_TV_D_TABLA_DINAMICA]
	@NOMBRE_TABLA NVARCHAR(MAX)
  ,@NOM_COLUMNAS NVARCHAR(MAX)
  ,@USUARIO NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
  DECLARE 
    @SEPERADOR VARCHAR(1) = ','
   ,@COLUMNA NVARCHAR(MAX)
   ,@COLUMNA_BD NVARCHAR(MAX)
   ,@SQL NVARCHAR(MAX)
   ,@NOMBRE_TABLA_BD NVARCHAR(MAX)
   ,@ID_TABLA INT
   ,@ID_COLUMNA INT
   ,@CONTADOR INT = 1

  SET @NOM_COLUMNAS = @NOM_COLUMNAS + @SEPERADOR;
  
  SELECT @NOMBRE_TABLA_BD = 'D_' + REPLACE(@NOMBRE_TABLA,' ','_');
  SET @SQL= 'CREATE TABLE '+ @NOMBRE_TABLA_BD + '( ID_' + REPLACE(@NOMBRE_TABLA,' ','_') + ' INT PRIMARY KEY NOT NULL IDENTITY(1,1)';

  INSERT INTO TV_D_TABLA(NOMBRE_BD,NOMBRE,FEC_ALTA,USUARIO) VALUES(@NOMBRE_TABLA_BD,@NOMBRE_TABLA,GETDATE(),@USUARIO);
  SELECT @ID_TABLA = @@IDENTITY

  WHILE CHARINDEX(@SEPERADOR, @NOM_COLUMNAS) > 0
  BEGIN
    SET @COLUMNA = SUBSTRING(@NOM_COLUMNAS, 0, CHARINDEX(@SEPERADOR, @NOM_COLUMNAS));
    SET @COLUMNA_BD = 'COLM_' + CONVERT(NVARCHAR,@CONTADOR);
    SET @NOM_COLUMNAS = SUBSTRING(@NOM_COLUMNAS, CHARINDEX(@SEPERADOR, @NOM_COLUMNAS) + 1, LEN(@NOM_COLUMNAS));
    SET @SQL = @SQL + ' ,' + @COLUMNA_BD + ' NVARCHAR(MAX)'
    SET @CONTADOR = @CONTADOR + 1

    INSERT INTO TV_D_COLUMNA(NOMBRE_BD,NOMBRE,FEC_ALTA,USUARIO) VALUES(@COLUMNA_BD,@COLUMNA,GETDATE(),@USUARIO);
    SELECT @ID_COLUMNA = @@IDENTITY

    INSERT INTO TV_R_COLUMNA_TABLA(ID_TABLA,ID_COLUMNA,FEC_ALTA,USUARIO) VALUES (@ID_TABLA,@ID_COLUMNA,GETDATE(),@USUARIO)

    --PRINT @COLUMNA_BD;

  END;
  SET @SQL = @SQL + ' )';
  --PRINT @SQL;

  EXEC sys.[sp_executesql] @SQL;

  SELECT @ID_TABLA

END