-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SPI_TV_D_MENSAJE_VIVO_]
	    @ID_ESTATUS INT
    ,@DSC_MENSAJE TEXT
    ,@ES_REPETITIVO BIT
    ,@TIEMPO_REPETICION TIME
    --,@FECHA_ALTA DATETIME
    --,@FECHA_MOD DATETIME
    ,@USUARIO NVARCHAR(100)
	,@COLOR_FONDO_BARRA_TEXTO varchar(50)
	,@OPACIDAD_TEXTO decimal(15, 2)
	,@OPACIDAD_BARRA_TEXTO decimal(15, 2)
	,@TIPO_LETRA_TEXTO nvarchar(100)
	,@TAMANIO_LETRA_TEXTO int
	,@COLOR_TEXTO varchar(50)
	,@VELOCIDAD_TEXTO decimal(15, 2)
AS
BEGIN
 SET NOCOUNT ON

  DECLARE @ID_MENSAJE INT

  INSERT INTO TV_D_MENSAJE_VIVO
  (
    ID_ESTATUS
    ,DSC_MENSAJE
    ,ES_REPETITIVO
    ,TIEMPO_REPETICION
    ,FECHA_ALTA
    --,FECHA_MOD
    ,USUARIO
	,COLOR_FONDO_BARRA_TEXTO
	,OPACIDAD_TEXTO
	,OPACIDAD_BARRA_TEXTO
	,TIPO_LETRA_TEXTO
	,TAMANIO_LETRA_TEXTO
	,COLOR_TEXTO
	,VELOCIDAD_TEXTO
  )
  VALUES
  (
    @ID_ESTATUS
    ,@DSC_MENSAJE
    ,@ES_REPETITIVO
    ,@TIEMPO_REPETICION
    ,GETDATE()
    --,@FECHA_MOD
    ,@USUARIO
	,@COLOR_FONDO_BARRA_TEXTO
	,@OPACIDAD_TEXTO
	,@OPACIDAD_BARRA_TEXTO
	,@TIPO_LETRA_TEXTO
	,@TAMANIO_LETRA_TEXTO
	,@COLOR_TEXTO
	,@VELOCIDAD_TEXTO
  )
 	SELECT @@IDENTITY
    SET NOCOUNT OFF
END
