-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Inserta registro en la tabla TV_D_CANAL
-- =============================================
CREATE PROCEDURE [dbo].[SPI_TV_D_CANAL]
    --@ID_CANAL INT
    --,@ID_CONTENIDO INT
    @ID_TIPO_CANAL INT
    --,@DURACION_SEG INT
    --,@DURACION_MIN INT
    --,@DURACION_HRS INT
    --,@INICIO_SEG INT
    --,@INICIO_MIN INT
    --,@INICIO_HRS INT
    --,@POSICION_X INT
    --,@POSICION_Y INT
    --,@ES_REPETITIVO BIT
    --,@ID_TIPO_PRESENTACION INT
    --,@ID_FORMA_DESPLIEGUE INT
    --,@ES_COLOR_FONDO_TEXTO BIT
    --,@OPACIDAD_BARRA_TEXTO DECIMAL(15,2)
    --,@COLOR_FONDO_BARRA_TEXTO VARCHAR(50) = ''
    --,@RUTA_IMG_FONDO_BARRA_TEXTO VARCHAR(150) = ''
    --,@VELOCIDAD_TEXTO DECIMAL(15,2)
    --,@TIPO_LETRA_TEXTO NVARCHAR(255) = ''
    --,@TAMANIO_LETRA_TEXTO INT
    --,@OPACIDAD_TEXTO DECIMAL(15,2)
    --,@COLOR_TEXTO VARCHAR(50) = ''
    --,@ANCHO_BARRA_TEXTO INT
    --,@ALTO_BARRA_TEXTO INT
    --,@ORIENTACION_TEXTO INT
    --,@POSICION_X_FIN_TEXTO INT
    --,@POSICION_Y_FIN_TEXTO INT
    --,@FEC_REPRODUCCION DATETIME
    --,@FEC_ALTA DATETIME
    --,@FEC_MOD DATETIME
    --,@ORDEN INT
    ,@ID_ESTATUS INT
    --,@ALTO INT
    --,@ANCHO INT
    ,@CANTIDAD_CONTENIDO INT
    ,@CLAVE VARCHAR(50) = ''
    --,@FEC_FIN DATETIME2
    --,@FEC_INICIO DATETIME2
    --,@FIN_HRS INT
    --,@FIN_MIN INT
    --,@FIN_SEG INT
    --,@ES_INTERMITENCIA BIT
    --,@INTERMITENCIA_SEG INT
    --,@INTERMITENCIA_MIN INT
    --,@INTERMITENCIA_HRS INT
    --,@OPACIDAD DECIMAL(15,2)
    --,@VOLUMEN DECIMAL(15,2)
    ,@USUARIO VARCHAR(50) = ''
AS
BEGIN
  SET NOCOUNT ON
  INSERT INTO TV_D_CANAL
  (
    ID_TIPO_CANAL
    --,DURACION_SEG
    --,DURACION_MIN
    --,DURACION_HRS
    --,INICIO_SEG
    --,INICIO_MIN
    --,INICIO_HRS
    --,POSICION_X
    --,POSICION_Y
    --,ES_REPETITIVO
    --,ID_TIPO_PRESENTACION
    --,ID_FORMA_DESPLIEGUE
    --,ES_COLOR_FONDO_TEXTO
    --,OPACIDAD_BARRA_TEXTO
    --,COLOR_FONDO_BARRA_TEXTO
    --,RUTA_IMG_FONDO_BARRA_TEXTO
    --,VELOCIDAD_TEXTO
    --,TIPO_LETRA_TEXTO
    --,TAMANIO_LETRA_TEXTO
    --,OPACIDAD_TEXTO
    --,COLOR_TEXTO
    --,ANCHO_BARRA_TEXTO
    --,ALTO_BARRA_TEXTO
    --,ORIENTACION_TEXTO
    --,POSICION_X_FIN_TEXTO
    --,POSICION_Y_FIN_TEXTO
    --,FEC_REPRODUCCION
    ,FEC_ALTA
    --,FEC_MOD
    --,ORDEN
    ,ID_ESTATUS
    --,ALTO
    --,ANCHO
    ,CANTIDAD_CONTENIDO
    ,CLAVE
    --,FEC_FIN
    --,FEC_INICIO
    --,FIN_HRS
    --,FIN_MIN
    --,FIN_SEG
    --,ES_INTERMITENCIA
    --,INTERMITENCIA_SEG
    --,INTERMITENCIA_MIN
    --,INTERMITENCIA_HRS
    --,OPACIDAD
    --,VOLUMEN
    ,USUARIO
  )
  VALUES
  (
    @ID_TIPO_CANAL
    --,@DURACION_SEG
    --,@DURACION_MIN
    --,@DURACION_HRS
    --,@INICIO_SEG
    --,@INICIO_MIN
    --,@INICIO_HRS
    --,@POSICION_X
    --,@POSICION_Y
    --,@ES_REPETITIVO
    --,@ID_TIPO_PRESENTACION
    --,@ID_FORMA_DESPLIEGUE
    --,@ES_COLOR_FONDO_TEXTO
    --,@OPACIDAD_BARRA_TEXTO
    --,@COLOR_FONDO_BARRA_TEXTO
    --,@RUTA_IMG_FONDO_BARRA_TEXTO
    --,@VELOCIDAD_TEXTO
    --,@TIPO_LETRA_TEXTO
    --,@TAMANIO_LETRA_TEXTO
    --,@OPACIDAD_TEXTO
    --,@COLOR_TEXTO
    --,@ANCHO_BARRA_TEXTO
    --,@ALTO_BARRA_TEXTO
    --,@ORIENTACION_TEXTO
    --,@POSICION_X_FIN_TEXTO
    --,@POSICION_Y_FIN_TEXTO
    --,@FEC_REPRODUCCION
    ,GETDATE()
    --,@FEC_MOD
    --,@ORDEN
    ,@ID_ESTATUS
    --,@ALTO
    --,@ANCHO
    ,@CANTIDAD_CONTENIDO
    ,@CLAVE
    --,@FEC_FIN
    --,@FEC_INICIO
    --,@FIN_HRS
    --,@FIN_MIN
    --,@FIN_SEG
    --,@ES_INTERMITENCIA
    --,@INTERMITENCIA_SEG
    --,@INTERMITENCIA_MIN
    --,@INTERMITENCIA_HRS
    --,@OPACIDAD
    --,@VOLUMEN
    ,@USUARIO
  )
  SELECT @@IDENTITY
  SET NOCOUNT OFF
END

