-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Inserta registro en la tabla TV_D_CONTENIDO
-- =============================================
CREATE PROCEDURE SPI_TV_D_CONTENIDO_TEXTO
  @ID_MENSAJE INT
  ,@ID_TIPO_CANAL INT
  ,@RUTA VARCHAR(150)
  ,@NOMBRE NCHAR(50)
  ,@DURACION_SEG INT
  ,@DURACION_MIN INT
  ,@DURACION_HRS INT
  ,@ORDEN INT
  --,@POSICION_X INT
  --,@POSICION_Y INT
  --,@ANCHO INT
  --,@ALTO INT
  ,@OPACIDAD DECIMAL
  ,@TEXTO VARCHAR(500)
  ,@ID_ESTATUS INT
  --,@FEC_ALTA DATETIME
  --,@FEC_MOD DATETIME
  ,@USUARIO VARCHAR(50)
  ,@COLOR_FONDO_BARRA_TEXTO varchar(50)
  ,@OPACIDAD_TEXTO decimal(15, 2)
  ,@TIPO_LETRA_TEXTO nvarchar(100)
  ,@TAMANIO_LETRA_TEXTO int
  ,@COLOR_TEXTO varchar(50)
  ,@VELOCIDAD_TEXTO decimal(15, 2)
  ,@ES_REPETITIVO bit
  ,@ID_TIPO_PRESENTACION int
  ,@ID_FORMA_DESPLIEGUE int
  ,@ES_COLOR_FONDO_TEXTO bit
  ,@RUTA_IMG_FONDO_BARRA_TEXTO varchar(150)
  ,@ORIENTACION_TEXTO int
  ,@ES_INTERMITENCIA bit
  ,@INTERMITENCIA_SEG int
  ,@INTERMITENCIA_MIN int
  ,@INTERMITENCIA_HRS INT
AS
BEGIN
  SET NOCOUNT ON
  INSERT INTO TV_D_CONTENIDO
  (
    ID_MENSAJE
    ,ID_TIPO_CANAL
    ,RUTA
    ,NOMBRE
    ,DURACION_SEG
    ,DURACION_MIN
    ,DURACION_HRS
    ,ORDEN
    --,POSICION_X
    --,POSICION_Y
    --,ANCHO
    --,ALTO
    ,OPACIDAD
    ,TEXTO
    ,ID_ESTATUS
    ,FEC_ALTA
    --,FEC_MOD
    ,USUARIO
	,COLOR_FONDO_BARRA_TEXTO 
	,OPACIDAD_TEXTO
	,TIPO_LETRA_TEXTO
	,TAMANIO_LETRA_TEXTO
	,COLOR_TEXTO
	,VELOCIDAD_TEXTO
	,ES_REPETITIVO 
	,ID_TIPO_PRESENTACION 
	,ID_FORMA_DESPLIEGUE 
	,ES_COLOR_FONDO_TEXTO 
	,RUTA_IMG_FONDO_BARRA_TEXTO 
	,ORIENTACION_TEXTO 
	,ES_INTERMITENCIA 
	,INTERMITENCIA_SEG 
	,INTERMITENCIA_MIN 
	,INTERMITENCIA_HRS 
  )
  VALUES
  (
    @ID_MENSAJE
    ,@ID_TIPO_CANAL
    ,@RUTA
    ,@NOMBRE
    ,@DURACION_SEG
    ,@DURACION_MIN
    ,@DURACION_HRS
    ,@ORDEN
    --,@POSICION_X
    --,@POSICION_Y
    --,@ANCHO
    --,@ALTO
    ,@OPACIDAD
    ,@TEXTO
    ,@ID_ESTATUS
    ,GETDATE()
    --,@FEC_MOD
    ,@USUARIO
	,@COLOR_FONDO_BARRA_TEXTO 
	,@OPACIDAD_TEXTO 
	,@TIPO_LETRA_TEXTO
	,@TAMANIO_LETRA_TEXTO 
	,@COLOR_TEXTO 
    ,@VELOCIDAD_TEXTO 
	,@ES_REPETITIVO 
	,@ID_TIPO_PRESENTACION 
	,@ID_FORMA_DESPLIEGUE 
	,@ES_COLOR_FONDO_TEXTO 
	,@RUTA_IMG_FONDO_BARRA_TEXTO 
	,@ORIENTACION_TEXTO 
	,@ES_INTERMITENCIA 
	,@INTERMITENCIA_SEG 
	,@INTERMITENCIA_MIN 
	,@INTERMITENCIA_HRS 
  )
  SELECT @@IDENTITY
  SET NOCOUNT OFF
END

