-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  13/01/2021
-- Description:  Selecciona todos los registros de la tabla TV_D_CONTENIDO
-- =============================================
CREATE PROCEDURE [dbo].[SPS_TV_D_CONTENIDO_XML]
  @ID_CANAL INT
AS
BEGIN
  SET NOCOUNT ON
  SELECT 
    TA.ID_CONTENIDO
    ,TA.ID_REPOSITORIO
    ,TA.ID_MENSAJE
    ,TA.ID_TIPO_CANAL
    ,TA.RUTA
    ,TD.RUTA_ALOJAMIENTO AS RUTA_ONLINE
    ,TA.NOMBRE
    ,TA.DURACION_SEG
    ,TA.DURACION_MIN
    ,TA.DURACION_HRS
    ,TA.ORDEN
    --,TA.POSICION_X
    --,TA.POSICION_Y
    --,TA.ANCHO
    --,TA.ALTO
    ,TA.OPACIDAD
    ,TC.DESCRIPCION AS TEXTO
    ,TB.FEC_INICIO
    ,TB.FEC_FIN
    ,TA.DURACION_SEG
    ,TA.DURACION_MIN
    ,TA.DURACION_HRS
    ,TB.INICIO_SEG
    ,TB.INICIO_MIN
    ,TB.INICIO_HRS
    ,TB.FIN_SEG
    ,TB.FIN_MIN
    ,TB.FIN_HRS
    ,TA.ES_REPETITIVO
    ,TA.OPACIDAD
    ,TA.OPACIDAD_TEXTO
    ,TA.OPACIDAD_BARRA_TEXTO
    ,TA.VELOCIDAD_TEXTO
    ,TA.ID_TIPO_PRESENTACION
    ,TA.ID_FORMA_DESPLIEGUE
    ,TA.ES_COLOR_FONDO_TEXTO
    ,TA.COLOR_FONDO_BARRA_TEXTO
    ,TA.RUTA_IMG_FONDO_BARRA_TEXTO
    ,TA.TIPO_LETRA_TEXTO
    ,TA.TAMANIO_LETRA_TEXTO
    ,TA.COLOR_TEXTO
    ,TA.ORIENTACION_TEXTO
    ,TA.ES_INTERMITENCIA
    ,TA.INTERMITENCIA_SEG
    ,TA.INTERMITENCIA_MIN
    ,TA.INTERMITENCIA_HRS
    ,TA.VOLUMEN
    ,TA.ID_ESTATUS
    ,TA.FEC_ALTA
    ,TA.FEC_MOD
    ,TA.USUARIO
    ,TD1.DURACION
  FROM TV_D_CONTENIDO TA
  LEFT JOIN TV_R_CANAL_CONTENIDO TB ON TB.ID_CONTENIDO = TA.ID_CONTENIDO
  LEFT JOIN TV_C_MENSAJES TC ON TC.ID_MENSAJE = TA.ID_MENSAJE
  LEFT JOIN TV_D_REPOSITORIO TD1 ON TD1.ID_REPOSITORIO = TA.ID_REPOSITORIO
  LEFT JOIN TV_C_REPOSITORIO TD ON TD.NOMBRE = TD1.DESCRIPCION
  WHERE
    TB.ID_CANAL = @ID_CANAL
  ORDER BY TA.ORDEN
  SET NOCOUNT OFF
END
