
-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Selecciona un registro en especifico de la tabla TV_D_CONTENIDO
-- =============================================
CREATE PROCEDURE [dbo].[SPS_TV_D_CONTENIDO]
    @ID_CONTENIDO INT
  AS
BEGIN
  SET NOCOUNT ON
  SELECT 
     C.ID_CONTENIDO
    ,C.ID_REPOSITORIO
    ,C.ID_MENSAJE
    ,C.ID_TIPO_CANAL
    ,C.ID_TABLA
    ,C.RUTA
    ,C.NOMBRE
    ,C.DURACION_SEG
    ,C.DURACION_MIN
    ,C.DURACION_HRS
    ,C.ORDEN
    --,C.POSICION_X
    --,C.POSICION_Y
    --,C.ANCHO
    --,C.ALTO
    ,C.OPACIDAD
    ,C.TEXTO
    ,C.ID_ESTATUS
    ,C.FEC_ALTA
    ,C.FEC_MOD
    ,C.USUARIO
    ,C.COLOR_FONDO_BARRA_TEXTO 
    ,C.OPACIDAD_TEXTO
    ,C.TIPO_LETRA_TEXTO
    ,C.TAMANIO_LETRA_TEXTO
    ,C.COLOR_TEXTO
    ,C.VELOCIDAD_TEXTO
    ,C.ES_REPETITIVO 
    ,C.ID_TIPO_PRESENTACION 
    ,C.ID_FORMA_DESPLIEGUE 
    ,C.ES_COLOR_FONDO_TEXTO 
    ,C.RUTA_IMG_FONDO_BARRA_TEXTO 
    ,C.ORIENTACION_TEXTO 
    ,C.ES_INTERMITENCIA 
    ,C.INTERMITENCIA_SEG 
    ,C.INTERMITENCIA_MIN 
    ,C.INTERMITENCIA_HRS 
    ,C.VOLUMEN
    ,R.*
    ,TC.RUTA_ALOJAMIENTO AS rutaCatalogo
    ,M.*
  FROM TV_D_CONTENIDO C
  LEFT JOIN TV_D_REPOSITORIO R
  ON C.ID_REPOSITORIO = R.ID_REPOSITORIO
  LEFT JOIN TV_C_MENSAJES M
  ON C.ID_MENSAJE = M.ID_MENSAJE
  LEFT JOIN TV_C_REPOSITORIO TC
  ON R.RUTA_ALOJAMIENTO = TC.NOMBRE
  WHERE C.ID_CONTENIDO = @ID_CONTENIDO
  ORDER BY C.ID_CONTENIDO
  SET NOCOUNT OFF
END

