CREATE PROCEDURE [dbo].[SPS_TV_C_REPOSITORIO_BY_NAME]
	@NOMBRE NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON
  SELECT 
      ID_REPOSITORIO
      ,NOMBRE
      ,RUTA_ALOJAMIENTO
      ,FEC_ALTA
	  ,USUARIO
    FROM TV_C_REPOSITORIO 
	WHERE NOMBRE = @NOMBRE
  SET NOCOUNT OFF
END