CREATE PROCEDURE [dbo].[SPS_TV_C_REPOSITORIO]

 @ID_REPOSITORIO INT

AS
BEGIN
  SET NOCOUNT ON
  SELECT 

    ID_REPOSITORIO
    ,NOMBRE
    ,RUTA_ALOJAMIENTO
    ,FEC_ALTA
    ,USUARIO
    FROM TV_C_REPOSITORIO
    WHERE
      ID_REPOSITORIO = @ID_REPOSITORIO
  SET NOCOUNT OFF
END