-- =============================================
-- Author:		Gerardo Gonzalez
-- Create date: 02/04/2020
-- Description:	Traer la informacion
-- =============================================
CREATE PROCEDURE [dbo].[SPS_TV_D_MENSAJE_VIVO_ALL] 
	 @Busqueda NVARCHAR(150),
                       @Pagina INT,
	 @RegistrosPorPagina INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON
SELECT
    TA.ID_MENSAJE
    ,TA.ID_ESTATUS
    ,TA.DSC_MENSAJE
    ,TA.ES_REPETITIVO
    ,TA.TIEMPO_REPETICION
    ,TA.FECHA_ALTA
    ,TA.FECHA_MOD
    ,TA.USUARIO
    ,TA.COLOR_FONDO_BARRA_TEXTO
    ,TA.OPACIDAD_TEXTO
    ,TA.OPACIDAD_BARRA_TEXTO
    ,TA.TIPO_LETRA_TEXTO
    ,TA.TAMANIO_LETRA_TEXTO
    ,TA.COLOR_TEXTO
    ,TA.VELOCIDAD_TEXTO
    ,(
      SELECT ID_GRUPO
      FROM TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO
      WHERE ID_MENSAJE = TA.ID_MENSAJE
      GROUP BY ID_GRUPO
    ) ID_GRUPO
	,(
      SELECT TOP 1 G.NOMBRE
      FROM TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO MV
	  INNER JOIN TV_D_GRUPOS G ON G.ID_GRUPO = MV.ID_GRUPO
      WHERE MV.ID_MENSAJE = TA.ID_MENSAJE
    ) NOMBRE_GRUPO
    ,(
      SELECT TOP 1
        CASE 
          WHEN ID_GRUPO IS NULL THEN ID_REPRODUCTOR
          ELSE NULL
        END ID_REPRODUCTOR
      FROM TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO
      WHERE ID_MENSAJE = TA.ID_MENSAJE
    )ID_REPRODUCTOR
	,(
       SELECT TOP 1
        CASE 
          WHEN ID_GRUPO IS NULL THEN  R.DESCRIPCION
          ELSE NULL
        END
		DESCRIPCION
      FROM TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO MV
	  INNER JOIN TV_C_REPRODUCTOR R ON R.ID_REPRODUCTOR = MV.ID_REPRODUCTOR
      WHERE ID_MENSAJE = TA.ID_MENSAJE
    )NOMBRE_RERODUCTOR
  FROM TV_D_MENSAJE_VIVO TA 
   WHERE(
   TA.DSC_MENSAJE LIKE CASE WHEN @Busqueda = '0' THEN TA.DSC_MENSAJE ELSE '%' + @Busqueda +'%' END)
  ORDER BY  TA.ID_MENSAJE
  OFFSET ((@Pagina-1) * @RegistrosPorPagina) ROWS
  FETCH NEXT @RegistrosPorPagina ROWS ONLY 
	SET NOCOUNT OFF
END
