-- =============================================
-- Author:		ING. LUIS FERNANDO ANGELES ESCAMILLA
-- Create date: 25-06-202
-- Description:	CONSULTA DE TEMPLATE POR EL CONTENIDO DE TV DIRECTO
-- =============================================
CREATE PROCEDURE SPS_TV_D_TEMPLATES_DIRECTO
AS
BEGIN
	SET NOCOUNT ON;

  SELECT DISTINCT
    TA.ID_TEMPLATE
    ,TA.NOMBRE
    ,TA.ID_ESTATUS
    ,TC.ID_TIPO_CANAL
  FROM TV_D_TEMPLATES TA
  LEFT JOIN TV_R_TEMPLATE_CANAL TB1 ON TB1.ID_TEMPLATE = TA.ID_TEMPLATE
  LEFT JOIN TV_D_CANAL TB ON TB.ID_CANAL = TB1.ID_CANAL
  LEFT JOIN TV_R_CANAL_CONTENIDO TC1 ON TC1.ID_CANAL = TB.ID_CANAL
  LEFT JOIN TV_D_CONTENIDO TC ON TC.ID_CONTENIDO = TC1.ID_CONTENIDO
  WHERE
    TC.ID_TIPO_CANAL = 18
END
