CREATE PROCEDURE [dbo].[SPS_TV_D_HORARIO_GRUPO_ALL]
  AS
BEGIN
  SET NOCOUNT ON
	SELECT g.*, h.IdTvHorarioTerminal as ID_HORARIO
	FROM TV_D_GRUPOS g
	INNER JOIN TV_R_HORARIO_GRUPO rh
	ON g.ID_GRUPO = rh.ID_GRUPO
	INNER JOIN TV_D_HORARIO_TERMINAL h
	ON rh.ID_HORARIO = h.IdTvHorarioTerminal
  SET NOCOUNT OFF
END

