
-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Actualiza los campos de un registro en especifico de la tabla TV_D_CONTENIDO
-- =============================================
CREATE PROCEDURE SPU_TV_D_CONTENIDO_TEXTO
     @ID_CONTENIDO INT
    ,@ID_MENSAJE INT
    ,@ID_TIPO_CANAL INT
    ,@RUTA VARCHAR(150)
    ,@NOMBRE NCHAR(50)
    ,@DURACION_SEG INT
    ,@DURACION_MIN INT
    ,@DURACION_HRS INT
    ,@ORDEN INT
    --,@POSICION_X INT
    --,@POSICION_Y INT
    --,@ANCHO INT
    --,@ALTO INT
    ,@OPACIDAD DECIMAL
    ,@TEXTO VARCHAR(500)
    ,@ID_ESTATUS INT
    --,@FEC_ALTA DATETIME
    --,@FEC_MOD DATETIME
    ,@USUARIO VARCHAR(50)
	,@COLOR_FONDO_BARRA_TEXTO varchar(50)
	,@OPACIDAD_TEXTO decimal(15, 2)
    ,@TIPO_LETRA_TEXTO nvarchar(100)
    ,@TAMANIO_LETRA_TEXTO int
    ,@COLOR_TEXTO varchar(50)
    ,@VELOCIDAD_TEXTO decimal(15, 2)
	,@ES_REPETITIVO bit
	,@ID_TIPO_PRESENTACION int
	,@ID_FORMA_DESPLIEGUE int
	,@ES_COLOR_FONDO_TEXTO bit
	,@RUTA_IMG_FONDO_BARRA_TEXTO varchar(150)
	,@ORIENTACION_TEXTO int
	,@ES_INTERMITENCIA bit
	,@INTERMITENCIA_SEG int
	,@INTERMITENCIA_MIN int
	,@INTERMITENCIA_HRS INT
AS
BEGIN
  SET NOCOUNT ON
  UPDATE TV_D_CONTENIDO SET
    ID_MENSAJE = @ID_MENSAJE
    ,ID_TIPO_CANAL = @ID_TIPO_CANAL
    ,RUTA = @RUTA
    ,NOMBRE = @NOMBRE
    ,DURACION_SEG = @DURACION_SEG
    ,DURACION_MIN = @DURACION_MIN
    ,DURACION_HRS = @DURACION_HRS
    ,ORDEN = @ORDEN
    --,POSICION_X = @POSICION_X
    --,POSICION_Y = @POSICION_Y
    --,ANCHO = @ANCHO
    --,ALTO = @ALTO
    ,OPACIDAD = @OPACIDAD
    ,TEXTO = @TEXTO
    ,ID_ESTATUS = @ID_ESTATUS
    --,FEC_ALTA = @FEC_ALTA
    ,FEC_MOD = GETDATE()
    ,USUARIO = @USUARIO
	,COLOR_FONDO_BARRA_TEXTO = @COLOR_FONDO_BARRA_TEXTO
	,OPACIDAD_TEXTO = @OPACIDAD_TEXTO
    ,TIPO_LETRA_TEXTO = @TIPO_LETRA_TEXTO
    ,TAMANIO_LETRA_TEXTO = @TAMANIO_LETRA_TEXTO
    ,COLOR_TEXTO = @COLOR_TEXTO
    ,VELOCIDAD_TEXTO = @VELOCIDAD_TEXTO
	,ES_REPETITIVO = @ES_REPETITIVO
	,ID_TIPO_PRESENTACION = @ID_TIPO_PRESENTACION
	,ID_FORMA_DESPLIEGUE = @ID_FORMA_DESPLIEGUE
	,ES_COLOR_FONDO_TEXTO = @ES_COLOR_FONDO_TEXTO
	,RUTA_IMG_FONDO_BARRA_TEXTO = @RUTA_IMG_FONDO_BARRA_TEXTO
	,ORIENTACION_TEXTO = @ORIENTACION_TEXTO
	,ES_INTERMITENCIA = @ES_INTERMITENCIA
	,INTERMITENCIA_SEG = @INTERMITENCIA_SEG
	,INTERMITENCIA_MIN = @INTERMITENCIA_MIN
	,INTERMITENCIA_HRS = @INTERMITENCIA_HRS
  WHERE
      ID_CONTENIDO = @ID_CONTENIDO
  SET NOCOUNT OFF
END

