
-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Actualiza los campos de un registro en especifico de la tabla TV_C_REPRODUCTOR
-- =============================================
CREATE PROCEDURE [dbo].[SPU_TV_C_REPRODUCTOR_ACTUALIZACION]
    @ID_REPRODUCTOR INT
    --,@CANTIDAD_VIDEOS INT
    --,@DESCRIPCION VARCHAR(50)
    --,@FEC_ALTA DATETIME2
    ,@FEC_MOD DATETIME
    --,@ID_TIPO_DISPOSITIVO INT
	,@ACTUALIZACION BIT
    --,@IP_CLIENTE VARCHAR(50)
    --,@PUERTO_CLIENTE VARCHAR(50)
    --,@RUTA_REPOSITORIO VARCHAR(150)
    ,@USUARIO VARCHAR(50)
    --,@ID_ESTATUS INT
AS
BEGIN
  SET NOCOUNT ON
  UPDATE TV_C_REPRODUCTOR SET
    --CANTIDAD_VIDEOS = @CANTIDAD_VIDEOS
    --,DESCRIPCION = @DESCRIPCION
    --,FEC_ALTA = @FEC_ALTA
    FEC_MOD = GETDATE()
    --,ID_TIPO_DISPOSITIVO = @ID_TIPO_DISPOSITIVO
    --,IP_CLIENTE = @IP_CLIENTE
    --,PUERTO_CLIENTE = @PUERTO_CLIENTE
    --,RUTA_REPOSITORIO = @RUTA_REPOSITORIO
	,ACTUALIZACION = @ACTUALIZACION
    ,USUARIO = @USUARIO
    --,ID_ESTATUS = @ID_ESTATUS
  WHERE
      ID_REPRODUCTOR = @ID_REPRODUCTOR
  SET NOCOUNT OFF
END

