
-- =============================================
-- Author:       Ing. Luis Fernando Angeles Escamilla
-- Create date:  15/08/2018
-- Description:  Actualiza los campos de un registro en especifico de la tabla TV_D_LOG_EXCEPCIONES_CAD
-- =============================================
CREATE PROCEDURE [dbo].[SPU_TV_D_LOG_EXCEPCIONES_CAD]
    @ID_LOG INT
    ,@DESCRIPCION VARCHAR(MAX)
    ,@ID_USUARIO INT
    ,@ID_REPRODUCTOR INT
    ,@ID_TEMPLATE INT
    ,@ID_REGION INT
    ,@ID_CANAL INT
    ,@ID_CONTENIDO INT
    ,@FECHA_CREACION DATETIME
    ,@NIVEL_SEVERIDAD VARCHAR(50)
    ,@IP VARCHAR(50)
    ,@USUARIO_ATENDIDO VARCHAR(50)
    ,@SOLUCION VARCHAR(MAX)
    ,@FECHA_ATENDIDO DATETIME
AS
BEGIN
  SET NOCOUNT ON
  UPDATE TV_D_LOG_EXCEPCIONES_CAD SET
    DESCRIPCION = @DESCRIPCION
    ,ID_USUARIO = @ID_USUARIO
    ,ID_REPRODUCTOR = @ID_REPRODUCTOR
    ,ID_TEMPLATE = @ID_TEMPLATE
    ,ID_REGION = @ID_REGION
    ,ID_CANAL = @ID_CANAL
    ,ID_CONTENIDO = @ID_CONTENIDO
    ,FECHA_CREACION = @FECHA_CREACION
    ,NIVEL_SEVERIDAD = @NIVEL_SEVERIDAD
    ,IP = @IP
    ,USUARIO_ATENDIDO = @USUARIO_ATENDIDO
    ,SOLUCION = @SOLUCION
    ,FECHA_ATENDIDO = @FECHA_ATENDIDO
  WHERE
      ID_LOG = @ID_LOG
  SET NOCOUNT OFF
END

