-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SPU_TV_D_MENSAJE_VIVO]
	-- Add the parameters for the stored procedure here
	@ID_MENSAJE INT,
	@DSC_MENSAJE TEXT,
	@ES_REPETITIVO BIT,
	@TIEMPO_REPETICION TIME,
	@USUARIO NVARCHAR(100),
	@ID_ESTATUS INT,
	@COLOR_FONDO_BARRA_TEXTO varchar(50)
	,@OPACIDAD_TEXTO decimal(15, 2)
	,@OPACIDAD_BARRA_TEXTO decimal(15, 2)
	,@TIPO_LETRA_TEXTO nvarchar(100)
	,@TAMANIO_LETRA_TEXTO int
	,@COLOR_TEXTO varchar(50)
	,@VELOCIDAD_TEXTO decimal(15, 2)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON
	UPDATE TV_D_MENSAJE_VIVO
	SET
	DSC_MENSAJE = @DSC_MENSAJE,
	ES_REPETITIVO = @ES_REPETITIVO,
	TIEMPO_REPETICION = @TIEMPO_REPETICION,
	USUARIO = @USUARIO,
	ID_ESTATUS = @ID_ESTATUS,
	FECHA_MOD = GETDATE(),
	COLOR_FONDO_BARRA_TEXTO = @COLOR_FONDO_BARRA_TEXTO,
	OPACIDAD_TEXTO = @OPACIDAD_TEXTO,
	OPACIDAD_BARRA_TEXTO = @OPACIDAD_BARRA_TEXTO,
	TIPO_LETRA_TEXTO = @TIPO_LETRA_TEXTO,
	TAMANIO_LETRA_TEXTO = @TAMANIO_LETRA_TEXTO,
	COLOR_TEXTO = @COLOR_TEXTO,
	VELOCIDAD_TEXTO = @VELOCIDAD_TEXTO

	WHERE ID_MENSAJE = @ID_MENSAJE
	SELECT @ID_MENSAJE
	SET NOCOUNT OFF
END
