CREATE TABLE [dbo].[GL_C_ESTADO] (
    [ID_ESTADO]   INT           NOT NULL,
    [DESC_ESTADO] VARCHAR (100) NULL,
    [ABV]         VARCHAR (50)  NULL,
    [FEC_ALTA]    DATETIME      NULL,
    [FEC_MOD]     DATETIME      NULL,
    [USUARIO]     VARCHAR (50)  NULL,
    CONSTRAINT [PK_GL_ESTADO_1] PRIMARY KEY CLUSTERED ([ID_ESTADO] ASC)
);

