CREATE TABLE [dbo].[GL_C_PARAMETRO] (
    [ID_PARAMETRO]      INT           IDENTITY (1, 1) NOT NULL,
    [PARAMETRO]         INT           NULL,
    [CONSECUTIVO]       INT           NULL,
    [CLAVE]             VARCHAR (5)   NULL,
    [DESCRIPCION]       VARCHAR (100) NULL,
    [PREDETERMINADO]    BIT           NULL,
    [FACTOR]            DECIMAL (18)  CONSTRAINT [DF_Parametro_Factor] DEFAULT ((1)) NULL,
    [ID_APLICACION_IST] INT           NULL,
    [FEC_ALTA]          DATETIME      NULL,
    [FEC_MOD]           DATETIME      NULL,
    [USUARIO]           VARCHAR (30)  NULL,
    CONSTRAINT [PK_PARAMETRO] PRIMARY KEY NONCLUSTERED ([ID_PARAMETRO] ASC),
    CONSTRAINT [FK_GL_C_PARAMETRO_GL_C_APLICACION_IST] FOREIGN KEY ([ID_APLICACION_IST]) REFERENCES [dbo].[GL_C_APLICACION_IST] ([ID_APLICACION_IST])
);


GO
CREATE CLUSTERED INDEX [IX_PARAMETRO]
    ON [dbo].[GL_C_PARAMETRO]([PARAMETRO] ASC, [CONSECUTIVO] ASC);

