CREATE TABLE [dbo].[GL_C_TIPO_ASENTAMIENTO] (
    [ID_TIPO_ASENTAMIENTO]   INT           NOT NULL,
    [DESC_TIPO_ASENTAMIENTO] VARCHAR (200) NOT NULL,
    [FEC_ALTA]               DATETIME      NOT NULL,
    [FEC_MOD]                DATETIME      NULL,
    [USUARIO]                VARCHAR (30)  NOT NULL,
    CONSTRAINT [PK__GL_C_TIP__426F7ED602760AC7] PRIMARY KEY CLUSTERED ([ID_TIPO_ASENTAMIENTO] ASC)
);

