CREATE TABLE [dbo].[GL_C_OPCION] (
    [ID_OPCION]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_SUCURSAL]  INT           NULL,
    [NOMBRE]       VARCHAR (50)  NOT NULL,
    [DESCRIPCION]  VARCHAR (50)  NULL,
    [URL_ICON]     VARCHAR (100) NULL,
    [URL]          VARCHAR (100) NULL,
    [ID_ESTATUS]   INT           NULL,
    [OPCION_PADRE] INT           NULL,
    [NIVEL]        INT           NULL,
    [ORDEN]        INT           NULL,
    [FEC_MOD]      DATETIME      NULL,
    [FEC_ALTA]     DATETIME      NOT NULL,
    [USUARIO]      VARCHAR (30)  NOT NULL,
    CONSTRAINT [PK_OPCION] PRIMARY KEY CLUSTERED ([ID_OPCION] ASC),
    CONSTRAINT [FK_OPCION_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_OPCION_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL])
);

