CREATE TABLE [dbo].[GL_C_PERFIL] (
    [ID_PERFIL]   INT          IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (40) NOT NULL,
    [DESCRIPCION] VARCHAR (80) NULL,
    [ID_ESTATUS]  INT          NULL,
    [FEC_ALTA]    DATETIME     NOT NULL,
    [FEC_MOD]     DATETIME     NULL,
    [USUARIO]     VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_Perfil] PRIMARY KEY CLUSTERED ([ID_PERFIL] ASC),
    CONSTRAINT [FK_PERFIL_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK15wsxjtrohj14ni2jywe5xq9s] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

