CREATE TABLE [dbo].[GL_C_USUARIO] (
    [ID_USUARIO]    INT          IDENTITY (1, 1) NOT NULL,
    [ID_PERSONA]    INT          NOT NULL,
    [ID_SUCURSAL]   INT          NOT NULL,
    [CLAVE_USUARIO] VARCHAR (30) NOT NULL,
    [CONTRASENA]    VARCHAR (50) NOT NULL,
    [ID_PERFIL]     INT          NOT NULL,
    [ID_ESTATUS]    INT          NOT NULL,
    [FEC_ALTA]      DATETIME     NOT NULL,
    [FEC_MOD]       DATETIME     NULL,
    [USUARIO]       VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC),
    CONSTRAINT [FK_USUARIO_PERFIL] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[GL_C_PERFIL] ([ID_PERFIL]),
    CONSTRAINT [FK_USUARIO_PERSONA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [dbo].[GL_D_PERSONA] ([ID_PERSONA]),
    CONSTRAINT [IX_USUARIO] UNIQUE NONCLUSTERED ([ID_PERSONA] ASC, [ID_SUCURSAL] ASC, [ID_PERFIL] ASC, [CLAVE_USUARIO] ASC)
);

