CREATE TABLE [dbo].[GL_C_APLICACION_IST] (
    [ID_APLICACION_IST] INT           IDENTITY (1, 1) NOT NULL,
    [CLAVE]             VARCHAR (25)  NOT NULL,
    [NOMBRE]            VARCHAR (250) NOT NULL,
    [FEC_ALTA]          DATETIME      NOT NULL,
    [FEC_MOD]           DATETIME      NULL,
    [USUARIO]           VARCHAR (30)  NOT NULL,
    [ID_ESTATUS]        INT           NULL,
    CONSTRAINT [PK_Aplicacion_IST] PRIMARY KEY CLUSTERED ([ID_APLICACION_IST] ASC),
    CONSTRAINT [FK_GL_C_APLICACION_IST_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

