CREATE TABLE [dbo].[GL_C_PAIS] (
    [ID_PAIS]    INT          IDENTITY (1, 1) NOT NULL,
    [DESC_PAIS]  VARCHAR (50) NULL,
    [GENTILICIO] VARCHAR (50) NULL,
    [FEC_ALTA]   DATETIME     NULL,
    [FEC_MOD]    DATETIME     NULL,
    [USUARIO]    VARCHAR (50) NULL,
    CONSTRAINT [PK_GL_PAIS] PRIMARY KEY CLUSTERED ([ID_PAIS] ASC)
);

