CREATE TABLE [dbo].[GL_C_DELEG_MUNICIPIO] (
    [ID_DELEG_MUNICIPIO]  INT           NOT NULL,
    [ID_ESTADO]           INT           NOT NULL,
    [DSC_DELEG_MUNICIPIO] VARCHAR (100) NULL,
    [FEC_ALTA]            DATETIME      NOT NULL,
    [FEC_MOD]             DATETIME      NULL,
    [USUARIO]             VARCHAR (30)  NULL,
    CONSTRAINT [PK_GL_DELEG_MUNICIPIO] PRIMARY KEY CLUSTERED ([ID_DELEG_MUNICIPIO] ASC, [ID_ESTADO] ASC),
    CONSTRAINT [FK_GL_DELEG_MUNICIPIO_GL_ESTADO1] FOREIGN KEY ([ID_ESTADO]) REFERENCES [dbo].[GL_C_ESTADO] ([ID_ESTADO]),
    CONSTRAINT [IX_DELEG_MUNICIPIO] UNIQUE NONCLUSTERED ([ID_DELEG_MUNICIPIO] ASC, [ID_ESTADO] ASC)
);

