CREATE TABLE [dbo].[GL_D_LICENCIAMIENTO] (
    [ID_LICENCIAMIENTO] INT          IDENTITY (1, 1) NOT NULL,
    [ID_ENTIDAD]        INT          NOT NULL,
    [ID_SUCURSAL]       INT          NULL,
    [ID_APLICACION_IST] INT          NOT NULL,
    [FECHA_ACTIVACION]  DATETIME     NULL,
    [VIGENCIA]          INT          NOT NULL,
    [CONCURRENCIA]      INT          NOT NULL,
    [FEC_ALTA]          DATETIME     NOT NULL,
    [FEC_MOD]           DATETIME     NULL,
    [USUARIO]           VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_LICENCIAMIENTO] PRIMARY KEY CLUSTERED ([ID_LICENCIAMIENTO] ASC),
    CONSTRAINT [FK_LICENCIAMIENTO_APLICACION_IST] FOREIGN KEY ([ID_APLICACION_IST]) REFERENCES [dbo].[GL_C_APLICACION_IST] ([ID_APLICACION_IST]),
    CONSTRAINT [FK_LICENCIAMIENTO_EMPRESA] FOREIGN KEY ([ID_ENTIDAD]) REFERENCES [dbo].[GL_D_ENTIDAD] ([ID_ENTIDAD]),
    CONSTRAINT [FK_LICENCIAMIENTO_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL])
);

