CREATE TABLE [dbo].[GL_D_ESTACION_TRABAJO] (
    [ID_ESTACION_TRABAJO] INT           IDENTITY (1, 1) NOT NULL,
    [ID_SUCURSAL]         INT           NOT NULL,
    [CLAVE]               VARCHAR (150) NOT NULL,
    [NOMBRE]              VARCHAR (250) NOT NULL,
    [DIRECCION_IP]        VARCHAR (50)  NULL,
    [DIRECCION_MAC]       VARCHAR (50)  NOT NULL,
    [ID_ESTATUS]          INT           NOT NULL,
    [ES_SERVIDOR]         BIT           CONSTRAINT [DF_ESTACION_TRABAJO_ES_SERVIDOR] DEFAULT ((0)) NOT NULL,
    [ID_PERSONA]          INT           NULL,
    [FEC_ALTA]            DATETIME      NOT NULL,
    [FEC_MOD]             DATETIME      NULL,
    [USUARIO]             VARCHAR (30)  NOT NULL,
    CONSTRAINT [PK_ESTACION_TRABAJO] PRIMARY KEY CLUSTERED ([ID_ESTACION_TRABAJO] ASC),
    CONSTRAINT [UKenqki9ktbh1pwc8y53h4ou4kl] UNIQUE NONCLUSTERED ([ID_ESTACION_TRABAJO] ASC, [ID_SUCURSAL] ASC)
);

