CREATE TABLE [dbo].[GL_D_PERSONA_SUCURSAL] (
    [ID_PERSONA]  INT          NOT NULL,
    [ID_SUCURSAL] INT          NOT NULL,
    [ID_ESTATUS]  INT          NOT NULL,
    [FEC_ALTA]    DATETIME     NOT NULL,
    [FEC_MOD]     DATETIME     NULL,
    [USUARIO]     VARCHAR (30) NOT NULL,
    CONSTRAINT [FK_pERSONA_SUCURSAL_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_PERSONA_SUCURSAL_PERSONA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [dbo].[GL_D_PERSONA] ([ID_PERSONA]),
    CONSTRAINT [FK_pERSONA_SUCURSAL_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL])
);

