CREATE TABLE [dbo].[GL_D_LICENCIA_ACTIVA] (
    [ID_LICENCIA_ACTIVA] INT            IDENTITY (1, 1) NOT NULL,
    [ID_ENTIDAD]         INT            NOT NULL,
    [ID_SUCURSAL]        INT            NULL,
    [ID_APLICACION_IST]  INT            NULL,
    [ID_ESTATUS]         INT            NULL,
    [LICENCIA]           NVARCHAR (MAX) NOT NULL,
    [LICENCIA_ACTIVA]    NVARCHAR (MAX) NOT NULL,
    [MAC_ADDRESS]        NVARCHAR (100)  NOT NULL,
    [SERIAL_NUMBER_BASE] NVARCHAR (100)  NOT NULL,
    [SERIAL_NUMBER_BIOS] NVARCHAR (100)  NOT NULL,
    [FECHA_ALTA]         DATETIME       NOT NULL,
    [FECHA_MOD]          DATETIME       NULL,
    [USUARIO]            VARCHAR (100)  NULL,
    CONSTRAINT [PK_GL_D_LICENCIA_ACTIVA] PRIMARY KEY CLUSTERED ([ID_LICENCIA_ACTIVA] ASC),
    CONSTRAINT [FK_GL_D_LICENCIA_ACTIVA_GL_C_APLICACION_IST] FOREIGN KEY ([ID_APLICACION_IST]) REFERENCES [dbo].[GL_C_APLICACION_IST] ([ID_APLICACION_IST]),
    CONSTRAINT [FK_GL_D_LICENCIA_ACTIVA_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_GL_D_LICENCIA_ACTIVA_GL_C_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL]),
    CONSTRAINT [FK_GL_D_LICENCIA_ACTIVA_GL_D_ENTIDAD] FOREIGN KEY ([ID_ENTIDAD]) REFERENCES [dbo].[GL_D_ENTIDAD] ([ID_ENTIDAD])
);

