CREATE TABLE [dbo].[GL_D_ENTIDAD] (
    [ID_ENTIDAD]   INT           IDENTITY (1, 1) NOT NULL,
    [CLAVE_IS]     VARCHAR (50)  NOT NULL,
    [RAZON_SOCIAL] VARCHAR (250) NOT NULL,
    [RFC]          VARCHAR (25)  NOT NULL,
    [ES_GRUPO]     BIT           CONSTRAINT [DF_EMPRESA_ES_GRUPO] DEFAULT ((0)) NOT NULL,
    [ID_ESTATUS]   INT           CONSTRAINT [DF_EMPRESA_IDESTATUS] DEFAULT ((1)) NOT NULL,
    [FEC_ALTA]     DATETIME      CONSTRAINT [DF_EMPRESA_FECHA_ALTA] DEFAULT (getdate()) NOT NULL,
    [FEC_MOD]      DATETIME      NULL,
    [USUARIO]      VARCHAR (30)  NULL,
    CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED ([ID_ENTIDAD] ASC)
);

