CREATE TABLE [dbo].[GL_D_SESION] (
    [ID_SESION]           INT          IDENTITY (1, 1) NOT NULL,
    [ID_ESTACION_TRABAJO] INT          NULL,
    [INICIO]              DATETIME     CONSTRAINT [DF_SESION_INICIO] DEFAULT (getdate()) NOT NULL,
    [ID_ESTATUS]          INT          NOT NULL,
    [FIN]                 DATETIME     NULL,
    [FEC_ALTA]            DATETIME     NOT NULL,
    [FEC_MOD]             DATETIME     NULL,
    [USUARIO]             VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_SESION] PRIMARY KEY CLUSTERED ([ID_SESION] ASC),
    CONSTRAINT [FK_SESION_ESTACION_TRABAJO] FOREIGN KEY ([ID_ESTACION_TRABAJO]) REFERENCES [dbo].[GL_D_ESTACION_TRABAJO] ([ID_ESTACION_TRABAJO]),
    CONSTRAINT [FK_SESION_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

