CREATE TABLE [dbo].[GL_R_CARACTERISTICA_SUCURSAL] (
    [ID_SUCURSAL]       INT          NOT NULL,
    [ID_CARACTERISTICA] INT          NOT NULL,
    [ESTATUS]           INT          NOT NULL,
    [FEC_ALTA]          DATETIME     NOT NULL,
    [FEC_MOD]           DATETIME     NULL,
    [USUARIO]           VARCHAR (30) NULL,
    CONSTRAINT [PK_GL_R_CARACTERISTICA_SUCURSAL] PRIMARY KEY CLUSTERED ([ID_SUCURSAL] ASC, [ID_CARACTERISTICA] ASC),
    CONSTRAINT [FK_CARACTERISTICA_SUCURSAL_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL]),
    CONSTRAINT [IX_CARACTERISTICA_SUCURSAL] UNIQUE NONCLUSTERED ([ID_SUCURSAL] ASC, [ID_CARACTERISTICA] ASC),
    CONSTRAINT [UK4ohb50df6r7w1632765rkvcel] UNIQUE NONCLUSTERED ([ID_SUCURSAL] ASC, [ID_CARACTERISTICA] ASC)
);

