CREATE TABLE [dbo].[GL_R_PERFIL_OPCION] (
    [ID_PERFIL] INT          NOT NULL,
    [ID_OPCION] INT          NOT NULL,
    [FEC_ALTA]  DATETIME     NOT NULL,
    [FEC_MOD]   DATETIME     NULL,
    [USUARIO]   VARCHAR (30) NULL,
    CONSTRAINT [FK_GL_R_PERFIL_OPCION_GL_C_OPCION] FOREIGN KEY ([ID_OPCION]) REFERENCES [dbo].[GL_C_OPCION] ([ID_OPCION]),
    CONSTRAINT [FK_Perfil_opcion_Perfil] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[GL_C_PERFIL] ([ID_PERFIL]) NOT FOR REPLICATION
);

