CREATE TABLE [dbo].[GL_R_SUCURSAL_DIRECCION] (
    [ID_SUCURSAL]  INT          NOT NULL,
    [ID_DIRECCION] INT          NOT NULL,
    [ID_ESTATUS]   INT          CONSTRAINT [DF_SUCURSAL_DIRECCION_ID_ESTATUS] DEFAULT ((1)) NOT NULL,
    [FEC_ALTA]     DATETIME     NOT NULL,
    [FEC_MOD]      DATETIME     NULL,
    [USUARIO]      VARCHAR (30) NULL,
    CONSTRAINT [PK_SUCURSAL_DIRECCION] PRIMARY KEY CLUSTERED ([ID_SUCURSAL] ASC, [ID_DIRECCION] ASC),
    CONSTRAINT [FK_SUCURSAL_DIRECCION_DIRECCION] FOREIGN KEY ([ID_DIRECCION]) REFERENCES [dbo].[GL_D_DIRECCION] ([ID_DIRECCION]),
    CONSTRAINT [FK_SUCURSAL_DIRECCION_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_SUCURSAL_DIRECCION_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL])
);

