CREATE TABLE [dbo].[GL_R_SUCURSAL_APLICACION_IST] (
    [ID_SUCURSAL_APLICACION] INT            IDENTITY (1, 1) NOT NULL,
    [ID_SUCURSAL]            INT            NULL,
    [ID_APLICACION_IST]      INT            NOT NULL,
    [LICENCIA_ACTIVADA]      NVARCHAR (MAX) NULL,
    [LICENCIA]               VARCHAR (MAX)  NOT NULL,
    [FEC_ALTA]               DATETIME       NOT NULL,
    [FEC_MOD]                DATETIME       NULL,
    [USUARIO]                VARCHAR (30)   NOT NULL,
    CONSTRAINT [PK_SUCURSAL_APLICACION_IST] PRIMARY KEY CLUSTERED ([ID_SUCURSAL_APLICACION] ASC),
    CONSTRAINT [FK_GL_SUCURSAL_APLICACION_IST_GL_APLICACION_IST] FOREIGN KEY ([ID_APLICACION_IST]) REFERENCES [dbo].[GL_C_APLICACION_IST] ([ID_APLICACION_IST]),
    CONSTRAINT [FK_GL_SUCURSAL_APLICACION_IST_GL_SUCURSAL] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [dbo].[GL_C_SUCURSAL] ([ID_SUCURSAL])
);

