CREATE TABLE [dbo].[GL_R_USUARIO_APLICACION_IS] (
    [ID_USUARIO]        INT          NOT NULL,
    [ID_APLICACION_IST] INT          NOT NULL,
    [FEC_ALTA]          DATETIME     NULL,
    [FEC_MOD]           DATETIME     NULL,
    [USUARIO]           VARCHAR (50) NULL,
    CONSTRAINT [PK_GL_R_USUARIO_APLICACION_IS] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC, [ID_APLICACION_IST] ASC),
    CONSTRAINT [FK_GL_R_USUARIO_APLICACION_IS_GL_C_APLICACION_IST] FOREIGN KEY ([ID_APLICACION_IST]) REFERENCES [dbo].[GL_C_APLICACION_IST] ([ID_APLICACION_IST]),
    CONSTRAINT [FK_GL_R_USUARIO_APLICACION_IS_GL_C_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[GL_C_USUARIO] ([ID_USUARIO])
);

