CREATE TABLE [dbo].[GL_R_PERSONA_DIRECCION] (
    [ID_PERSONA]   INT          NOT NULL,
    [ID_DIRECCION] INT          NOT NULL,
    [FEC_ALTA]     DATETIME     NOT NULL,
    [FEC_MOD]      DATETIME     NULL,
    [USUARIO]      VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_GL_R_PERSONA_DIRECCION] PRIMARY KEY CLUSTERED ([ID_PERSONA] ASC, [ID_DIRECCION] ASC),
    CONSTRAINT [FK_PERSONA_DIRECCION_DIRECCION] FOREIGN KEY ([ID_DIRECCION]) REFERENCES [dbo].[GL_D_DIRECCION] ([ID_DIRECCION]),
    CONSTRAINT [FK_PERSONA_DIRECCION_PERSONA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [dbo].[GL_D_PERSONA] ([ID_PERSONA])
);

