CREATE TABLE [dbo].[TV_C_MENSAJES] (
    [ID_MENSAJE]  INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      NVARCHAR (50) NULL,
    [DESCRIPCION] TEXT          NOT NULL,
    [FEC_ALTA]    DATETIME      NOT NULL,
    [FEC_MOD]     DATETIME      NULL,
    [ID_ESTATUS]  INT           NOT NULL,
    [USUARIO]     VARCHAR (30)  NOT NULL,
    CONSTRAINT [PK_TV_C_MENSAJES] PRIMARY KEY CLUSTERED ([ID_MENSAJE] ASC),
    CONSTRAINT [FK_TV_C_MENSAJES_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

