CREATE TABLE [dbo].[TV_C_EXTENSIONES] (
    [ID_EXTENSION]         INT          IDENTITY (1, 1) NOT NULL,
    [ID_TIPO_REPRODUCCION] INT          NOT NULL,
    [DESCRIPCION]          VARCHAR (10) NOT NULL,
    [ACTIVO]               BIT          NOT NULL,
    CONSTRAINT [PK_TV_C_EXTENSIONES] PRIMARY KEY CLUSTERED ([ID_EXTENSION] ASC)
);

