CREATE TABLE [dbo].[TV_C_REPOSITORIO]
(
  [ID_REPOSITORIO] INT NOT NULL IDENTITY(1,1)  PRIMARY KEY,
  [NOMBRE] NVARCHAR(250) NOT NULL,
  [RUTA_ALOJAMIENTO] TEXT NOT NULL,
  [FEC_ALTA] DATETIME NOT NULL DEFAULT GETDATE(),
  [USUARIO] NVARCHAR(30)  NULL DEFAULT 'Admin',
)
