CREATE TABLE [dbo].[TV_C_REPRODUCTOR] (
    [ID_REPRODUCTOR]      INT           IDENTITY (1, 1) NOT NULL,
    [CANTIDAD_VIDEOS]     INT           NULL,
    [DESCRIPCION]         VARCHAR (50)  NULL,
    [FEC_ALTA]            DATETIME2 (7) NULL,
    [FEC_MOD]             DATETIME2 (7) NULL,
    [ID_TIPO_DISPOSITIVO] INT           NULL,
    [IP_CLIENTE]          VARCHAR (50)  NULL,
    [PUERTO_CLIENTE]      VARCHAR (50)  NULL,
    [ACTUALIZACION]       BIT           CONSTRAINT [DF_TV_C_REPRODUCTOR_ACTUALIZACION] DEFAULT ((0)) NOT NULL,
    [RELOJ]               BIT           DEFAULT ((1)) NOT NULL,
    [RUTA_REPOSITORIO]    VARCHAR (150) NULL,
    [USUARIO]             VARCHAR (50)  NULL,
    [ID_ESTATUS]          INT           NULL,
    [DIRECCION_MAC] VARCHAR(20) NULL, 
    CONSTRAINT [PK__TV_C_REP__3615B979310EC3FB] PRIMARY KEY CLUSTERED ([ID_REPRODUCTOR] ASC),
    CONSTRAINT [FKp9fydlqx1launape4mifog2pu] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

