CREATE TABLE [dbo].[TV_D_CANAL] (
    [ID_CANAL]                   INT             IDENTITY (1, 1) NOT NULL,
    [CLAVE]                      VARCHAR (50)    NULL,
    [ID_TIPO_CANAL]              INT             NOT NULL,
    --[FEC_INICIO]                 DATETIME2 (7)   NULL,
    --[FEC_FIN]                    DATETIME2 (7)   NULL,
    --[FEC_REPRODUCCION]           DATETIME        NULL,
    --[DURACION_SEG]               INT             NOT NULL,
    --[DURACION_MIN]               INT             NOT NULL,
    --[DURACION_HRS]               INT             NOT NULL,
    --[INICIO_SEG]                 INT             NOT NULL,
    --[INICIO_MIN]                 INT             NOT NULL,
    --[INICIO_HRS]                 INT             NOT NULL,
    --[FIN_SEG]                    INT             NULL,
    --[FIN_MIN]                    INT             NULL,
    --[FIN_HRS]                    INT             NULL,
    --[ES_REPETITIVO]              BIT             NULL,
    --[OPACIDAD]                   DECIMAL (15, 2) NULL,
    --[OPACIDAD_TEXTO]             DECIMAL (15, 2) NULL,
    --[OPACIDAD_BARRA_TEXTO]       DECIMAL (15, 2) NULL,
    --[VELOCIDAD_TEXTO]            DECIMAL (15, 2) NULL,
    --[ID_TIPO_PRESENTACION]       INT             NULL,
    --[ID_FORMA_DESPLIEGUE]        INT             NULL,
    --[ES_COLOR_FONDO_TEXTO]       BIT             NULL,
    --[COLOR_FONDO_BARRA_TEXTO]    VARCHAR (50)    NULL,
    --[RUTA_IMG_FONDO_BARRA_TEXTO] VARCHAR (150)   NULL,
    --[TIPO_LETRA_TEXTO]           NVARCHAR (100)  NULL,
    --[TAMANIO_LETRA_TEXTO]        INT             NULL,
    --[COLOR_TEXTO]                VARCHAR (50)    NULL,
    --[ORIENTACION_TEXTO]          INT             NULL,
    --[ORDEN]                      INT             NULL,
    [CANTIDAD_CONTENIDO]         INT             NULL,
    --[ALTO]                       INT             NULL,
    --[ANCHO]                      INT             NULL,
    --[POSICION_X]                 INT             NOT NULL,
    --[POSICION_Y]                 INT             NOT NULL,
    --[ALTO_BARRA_TEXTO]           INT             NULL,
    --[ANCHO_BARRA_TEXTO]          INT             NULL,
    --[POSICION_X_FIN_TEXTO]       INT             NULL,
    --[POSICION_Y_FIN_TEXTO]       INT             NULL,
    --[ES_INTERMITENCIA]           BIT             NULL,
    --[INTERMITENCIA_SEG]          INT             NULL,
    --[INTERMITENCIA_MIN]          INT             NULL,
    --[INTERMITENCIA_HRS]          INT             NULL,
    [ID_ESTATUS]                 INT             NULL,
    [FEC_ALTA]                   DATETIME        NOT NULL,
    [FEC_MOD]                    DATETIME        NULL,
    [USUARIO]                    VARCHAR (50)    NULL,
    --[VOLUMEN]                    DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_TV_R_CANAL] PRIMARY KEY CLUSTERED ([ID_CANAL] ASC),
    CONSTRAINT [FK_TV_R_CANAL_GL_C_PARAMETRO_ESTATUS] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
    ,CONSTRAINT [FK_TV_R_CANAL_GL_C_PARAMETRO_TIPO_CANAL] FOREIGN KEY ([ID_TIPO_CANAL]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

