CREATE TABLE [dbo].[TV_D_RECOLECTOR_DATOS] (
    [ID_RECOLECTOR] INT          IDENTITY (1, 1) NOT NULL,
    [ID_TEMPLATE]   INT          NOT NULL,
    [ARCHIVO_XML]   TEXT         NOT NULL,
    [ACTUALIZACION] BIT          CONSTRAINT [DF_TV_D_RECOLECTOR_DATOS_ACTUALIZACION] DEFAULT ((0)) NOT NULL,
    [ID_ESTATUS]    INT          NULL,
    [FEC_ALTA]      DATETIME     NULL,
    [FEC_MOD]       DATETIME     NULL,
    [USUARIO]       VARCHAR (30) NULL,
    CONSTRAINT [PK_TV_D_RECOLECTOR_DATOS] PRIMARY KEY CLUSTERED ([ID_RECOLECTOR] ASC),
    CONSTRAINT [FK_TV_D_RECOLECTOR_DATOS_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

