CREATE TABLE [dbo].[TV_D_TABLA] (
    [ID_TABLA]  INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE_BD] NVARCHAR (250) NULL,
    [NOMBRE]    NVARCHAR (250) NULL,
    [FEC_ALTA]  DATETIME       NULL,
    [FEC_MOD]   DATETIME       NULL,
    [USUARIO]   NVARCHAR (250) NULL,
    CONSTRAINT [PK_TV_D_TABLA] PRIMARY KEY CLUSTERED ([ID_TABLA] ASC)
);

