CREATE TABLE [dbo].[TV_D_CAMPO] (
    [ID_CAMPO]     INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE_CAMPO] NVARCHAR (255) NULL,
    [ETIQUETA]     NVARCHAR (255) NULL,
    [ID_TIPO_DATO] INT            NULL,
    [TAMAÑO]       INT            NULL,
    [FEC_ALTA]     DATETIME       NULL,
    [FEC_MOD]      DATETIME       NULL,
    [USUARIO]      NVARCHAR (30)  NULL,
    CONSTRAINT [PK_TV_D_CAMPO] PRIMARY KEY CLUSTERED ([ID_CAMPO] ASC),
    CONSTRAINT [FK_TV_D_CAMPO_GL_C_PARAMETRO_TIPO_DATO] FOREIGN KEY ([ID_TIPO_DATO]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

