CREATE TABLE [dbo].[TV_D_LOG_EXCEPCIONES_CAD] (
    [ID_LOG]           INT           NOT NULL,
    [DESCRIPCION]      VARCHAR (MAX) NOT NULL,
    [ID_USUARIO]       INT           NOT NULL,
    [ID_REPRODUCTOR]   INT           NOT NULL,
    [ID_TEMPLATE]      INT           NOT NULL,
    [ID_REGION]        INT           NOT NULL,
    [ID_CANAL]         INT           NOT NULL,
    [ID_CONTENIDO]     INT           NOT NULL,
    [FECHA_CREACION]   DATETIME      NOT NULL,
    [NIVEL_SEVERIDAD]  VARCHAR (50)  NOT NULL,
    [IP]               VARCHAR (50)  NOT NULL,
    [USUARIO_ATENDIDO] VARCHAR (50)  NOT NULL,
    [SOLUCION]         VARCHAR (MAX) NOT NULL,
    [FECHA_ATENDIDO]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TV_D_LOG_EXCEPCIONES_CAD] PRIMARY KEY CLUSTERED ([ID_LOG] ASC)
);

