CREATE TABLE [dbo].[TV_R_MONITOR] (
    [ID_MONITOR]     INT          IDENTITY (1, 1) NOT NULL,
    [ID_TEMPLATE]    INT          NULL,
    [DESCRIPCION]    VARCHAR (50) NULL,
    [GRUPO]          VARCHAR (50) NULL,
    [FEC_ALTA]       DATETIME     NULL,
    [FEC_MOD]        DATETIME     NULL,
    [ID_ESTATUS]     INT          NOT NULL,
    [ID_REPRODUCTOR] INT          NOT NULL,
    [USUARIO]        VARCHAR (30) NULL,
    CONSTRAINT [PK_TV_R_MONITOR] PRIMARY KEY CLUSTERED ([ID_MONITOR] ASC),
    CONSTRAINT [FK_TV_R_MONITOR_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FKidj0qs4e8h74dxxb3fopurbkw] FOREIGN KEY ([ID_REPRODUCTOR]) REFERENCES [dbo].[TV_C_REPRODUCTOR] ([ID_REPRODUCTOR]),
    CONSTRAINT [FKobsaqolido9nb6pvf3cts19pt] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

