CREATE TABLE [dbo].[TV_R_TEMPLATE_REPRODUCTOR] (
    [ID_REPRODUCTOR] INT           NOT NULL,
    [ID_TEMPLATE]    INT           NOT NULL,
    [ID_ESTATUS]     INT           NOT NULL,
    [FECHA_ALTA]     DATETIME2 (7) NULL,
    [FECHA_MOD]      DATETIME2 (7) NULL,
    [USUARIO]        VARCHAR (30)  NULL,
    CONSTRAINT [PK_TV_R_TEMPLATE_REPRODUCTOR] PRIMARY KEY CLUSTERED ([ID_REPRODUCTOR] ASC, [ID_TEMPLATE] ASC),
    CONSTRAINT [FK_TV_R_TEMPLATE_REPRODUCTOR_GL_C_PARAMETRO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO])
);

