CREATE TABLE [dbo].[TV_R_TABLA_CAMPO] (
    [ID_TABLA_CAMPO] INT           IDENTITY (1, 1) NOT NULL,
    [ID_TABLA]       INT           NULL,
    [ID_CAMPO]       INT           NULL,
    [FEC_ALTA]       DATETIME      NULL,
    [FEC_MOD]        DATETIME      NULL,
    [USUARIO]        NVARCHAR (30) NULL,
    CONSTRAINT [PK_TV_R_TABLA_CAMPO] PRIMARY KEY CLUSTERED ([ID_TABLA_CAMPO] ASC),
    CONSTRAINT [FK_TV_R_TABLA_CAMPO_TV_D_CAMPO] FOREIGN KEY ([ID_CAMPO]) REFERENCES [dbo].[TV_D_CAMPO] ([ID_CAMPO]),
    CONSTRAINT [FK_TV_R_TABLA_CAMPO_TV_D_TABLA] FOREIGN KEY ([ID_TABLA]) REFERENCES [dbo].[TV_D_TABLA] ([ID_TABLA])
);

