CREATE TABLE [dbo].[TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO] (
    [ID_GRUPO_REPRODUCTOR_MENSAJE] INT            IDENTITY (1, 1) NOT NULL,
    [ID_GRUPO]                     INT            NULL,
    [ID_REPRODUCTOR]               INT            NULL,
    [ID_MENSAJE]                   INT            NULL,
    [ID_ESTATUS]                   INT            NULL,
    [FECHA_ALTA]                   DATETIME       NULL,
    [FECHA_MOD]                    DATETIME       NULL,
    [USUARIO]                      NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID_GRUPO_REPRODUCTOR_MENSAJE] ASC),
    CONSTRAINT [FK_TV_R_GRUPO_REPRODUCTOR_MENSAJE_GL_C_PARAMETRO_ESTATUS] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_TV_C_REPRODUCTOR] FOREIGN KEY ([ID_REPRODUCTOR]) REFERENCES [dbo].[TV_C_REPRODUCTOR] ([ID_REPRODUCTOR]),
    CONSTRAINT [FK_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_TV_D_GRUPOS] FOREIGN KEY ([ID_GRUPO]) REFERENCES [dbo].[TV_D_GRUPOS] ([ID_GRUPO])
);

