CREATE TABLE [dbo].[TV_R_GRUPO_REPRODUCTOR] (
    [ID_GRUPO_REPRODUCTOR] INT        IDENTITY (1, 1) NOT NULL,
    [ID_GRUPO]             INT        NULL,
    [ID_REPRODUCTOR]       INT        NULL,
    [FECHA_ALTA]           DATETIME   NULL,
    [FECHA_MOD]            DATETIME   NULL,
    [USAURIO]              NCHAR (30) NULL,
    CONSTRAINT [PK_TV_R_GRUPO_REPRODUCTOR] PRIMARY KEY CLUSTERED ([ID_GRUPO_REPRODUCTOR] ASC),
    CONSTRAINT [FK_ID_REPRODUCTOR_GRUPO_ID_REPROUCTOR] FOREIGN KEY ([ID_GRUPO_REPRODUCTOR]) REFERENCES [dbo].[TV_R_GRUPO_REPRODUCTOR] ([ID_GRUPO_REPRODUCTOR])
);

