CREATE TABLE TV_R_COLUMNA_TABLA(
  ID_COLUMNAS_TABLA INT IDENTITY(1,1) PRIMARY KEY NOT NULL
  ,ID_TABLA INT
  ,ID_COLUMNA INT
  ,FEC_ALTA DATETIME
  ,FEC_MOD DATETIME
  ,USUARIO NVARCHAR(30)
  ,CONSTRAINT [FK_TV_R_COLUMNA_TABLA_TV_D_TABLA] FOREIGN KEY ([ID_TABLA]) REFERENCES [dbo].[TV_D_TABLA] ([ID_TABLA])
  ,CONSTRAINT [FK_TV_R_COLUMNA_TABLA_TV_D_COLUMNA] FOREIGN KEY ([ID_COLUMNA]) REFERENCES [dbo].[TV_D_COLUMNA] ([ID_COLUMNA])
)