CREATE TABLE [dbo].[TV_R_COLUMNA_TABLA]
(
    [ID_COLUMNA_TABLA] INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [ID_COLUMNA] int NOT NULL,
    [ID_TABLA] int NOT NULL,
    [FEC_ALTA]  DATETIME       NULL,
    [FEC_MOD]   DATETIME       NULL,
    [USUARIO]   NVARCHAR (250) NULL,
    CONSTRAINT [FK_TV_R_COLUMNA_TABLA_ID_TABLA] FOREIGN KEY ([ID_TABLA]) REFERENCES [dbo].[TV_D_TABLA] ([ID_TABLA]),
    CONSTRAINT [FK_TV_R_COLUMNA_TABLA_ID_COLUMNA] FOREIGN KEY ([ID_COLUMNA]) REFERENCES [dbo].[TV_D_COLUMNA] ([ID_COLUMNA])
)

