CREATE TABLE [dbo].[TV_R_CANAL_CONTENIDO] (
    [ID_CANAL_CONTENIDO] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    [ID_CANAL]     INT           NOT NULL,
    [ID_CONTENIDO] INT           NOT NULL,
    [ORDEN]        INT           NULL,
    [ID_ESTATUS]   INT           NULL,
    [FEC_ALTA]     DATETIME2 (7) NULL,
    [FEC_MOD]      DATETIME2 (7) NULL,
    [USUARIO]      VARCHAR (30)  NULL,
    [INICIO_SEG] INT NULL,
    [INICIO_MIN] INT NULL,
    [INICIO_HRS] INT NULL,
    [FIN_SEG]    INT NULL,
    [FIN_MIN]    INT NULL,
    [FIN_HRS]    INT NULL,
    [FEC_FIN]    DATETIME2 (7)   NULL,
    [FEC_INICIO] DATETIME2 (7)   NULL,
    --CONSTRAINT [PK_TV_R_CANAL_CONTENIDO_1] PRIMARY KEY CLUSTERED ([ID_CANAL] ASC, [ID_CONTENIDO] ASC),
    CONSTRAINT [FK_TV_R_CANAL_CONTENIDO_GL_C_PARAMETRO_ESTATUS] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_TV_R_CANAL_CONTENIDO_TV_D_CANAL] FOREIGN KEY ([ID_CANAL]) REFERENCES [dbo].[TV_D_CANAL] ([ID_CANAL]),
    CONSTRAINT [FK_TV_R_CANAL_CONTENIDO_TV_D_CONTENIDO] FOREIGN KEY ([ID_CONTENIDO]) REFERENCES [dbo].[TV_D_CONTENIDO] ([ID_CONTENIDO])
);

