CREATE TABLE [dbo].[TV_R_TEMPLATE_CANAL] (
    [ID_CANAL_TEMPLATE] INT           IDENTITY (1, 1) NOT NULL,
    [ID_TEMPLATE]       INT           NULL,
    [ID_CANAL]          INT           NULL,
    [ID_ESTATUS]        INT           NULL,
    [ALTO]              INT           CONSTRAINT [DF_TV_R_CANAL_REGION_ALTO] DEFAULT ((270)) NULL,
    [ANCHO]             INT           CONSTRAINT [DF_TV_R_CANAL_REGION_ANCHO] DEFAULT ((288)) NULL,
    [POSICION_X]        INT           CONSTRAINT [DF_TV_R_CANAL_REGION_POSICION_X] DEFAULT ((0)) NULL,
    [POSICION_Y]        INT           CONSTRAINT [DF_TV_R_CANAL_REGION_POSICION_Y] DEFAULT ((0)) NULL,
    [ORDEN]             INT           CONSTRAINT [DF_TV_R_TEMPLATE_CANAL_ORDEN] DEFAULT ((0)) NULL,
    [FEC_ALTA]          DATETIME2 (7) NULL,
    [FEC_MOD]           DATETIME2 (7) NULL,
    [USUARIO]           VARCHAR (50)  NULL,
    CONSTRAINT [PK__TV_R_CAN__9DE4B3384A871CFF] PRIMARY KEY CLUSTERED ([ID_CANAL_TEMPLATE] ASC),
    CONSTRAINT [FK_TV_R_CANAL_REGION_GL_C_PARAMETRO_ESTATUS] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[GL_C_PARAMETRO] ([ID_PARAMETRO]),
    CONSTRAINT [FK_TV_R_CANAL_REGION_TV_D_CANAL] FOREIGN KEY ([ID_CANAL]) REFERENCES [dbo].[TV_D_CANAL] ([ID_CANAL]),
    CONSTRAINT [FK_TV_R_TEMPLATE_CANAL_TV_D_TEMPLATES] FOREIGN KEY ([ID_TEMPLATE]) REFERENCES [dbo].[TV_D_TEMPLATES] ([ID_TEMPLATE])
);

