using System;
using System.Collections.Generic;
using System.Text;

namespace iptv.AccesoDatos.TextoSql
{
    public static class MensajesVivo
    {
        public const string CONSULTAMENSAJESVIVO = @"[SPS_TV_D_MENSAJE_VIVO_ALL]";
        public const string CONSULTAMENSAJEVIVO = @"[SPS_TV_D_MENSAJE_VIVO]";
        public const string CONSULTATOTALMENSAJESVIVO = @"SELECT COUNT(ID_MENSAJE) FROM TV_D_MENSAJE_VIVO";
        public const string CONSULTAMENSAJESVIVOGRUPOREPRO = @"[SPS_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_ALL]";
        public const string CONSULTAMENSAJEVIVOGRUPOREPRO = @"[SPS_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_ID_MENSAJE]";
        public const string CONSULTATOTALMENSAJESVIVOGRUREP = @"SELECT COUNT(ID_GRUPO_REPRODUCTOR_MENSAJE) FROM TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO";
        public const string ALTAMENSAJEVIVO = @"[SPI_TV_D_MENSAJE_VIVO_]";
        public const string ALTAMENSAJEVIVOREPRODUCTOR = @"[SPI_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO]";
        public const string ACTUALIZAMENSAJEVIVO = @"[SPU_TV_D_MENSAJE_VIVO]";
        public const string ACTUALIZAMENSAJEVIVOREPRODUCTOR = @"[SPU_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO]";
        public const string ELIMINAMENSAJEVIVOREPRODUCTOR = @"[SPD_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_REPRODUCTOR]";
        public const string ELIMINAMENSAJEVIVOGRUPO = @"[SPD_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_GRUPO]";
        public const string ELIMINAMENSAJEVIVO = @"[SPD_TV_R_GRUPO_REPRODUCTOR_MENSAJE_VIVO_MENSAJE]";
    }
}
