using System;
using System.Collections.Generic;
using System.Text;

namespace iptv.AccesoDatos.TextoSql
{
    public static class Reproductor
    {
        public const string ALTAREPRODUCTOR = @"[SPI_TV_C_REPRODUCTOR]";
        public const string ALTAREPRODUCTORTEMPLATE = @"[SPI_TV_R_TEMPLATE_REPRODUCTOR]";
        public const string ALTAREPRODUCTORGRUPO = @"[SPI_TV_R_GRUPOS_REPRODUCTOR]";
        public const string ACTUALIZAREPRODUCTOR = @"[SPU_TV_C_REPRODUCTOR]";
        public const string ACTUALIZAREPRODUCTORTEMPLATE = @"[SPU_TV_R_TEMPLATE_REPRODUCTOR]";
        public const string ELIMINAREPRODUCTORTEMPLATE = @"[SPD_TV_R_TEMPLATE_REPRODUCTOR]";
        public const string ELIMINAREPRODUCTORGRUPO = @"[SPD_TV_R_GRUPOS_REPRODUCTOR_ID_REPRODUCTOR]";
        public const string ELIMINAREPRODUCTORGRUPOID = @"[SPD_TV_R_GRUPOS_REPRODUCTOR_IDREPRODUCTOR]";
        public const string ELIMINAREPRODUCTOR = @"[SPD_TV_C_REPRODUCTOR]";
        public const string OBTENERREPRODUCTOR = @"[SPS_TV_C_REPRODUCTOR]";
        public const string OBTENERREPRODUCTORGRUPO = @"[SPS_TV_C_REPRODUCTOR]";
        public const string OBTENERREPRODUCTORGRUPOID = @"[SPS_TV_R_GRUPO_REPRODUCTOR_IDREPRODUCTOR]";
        public const string CONSULTATOTALREPRODUCTORES = @"SELECT COUNT(ID_REPRODUCTOR) FROM TV_C_REPRODUCTOR";
        public const string CONSULTATOTALREPRODUCTORESCATALOGO = @"[SPS_TV_C_REPRODUCTOR_CATALOGO]";
        public const string CONSULTATOTALREPRODUCTORESCATALOGOASIGNADO = @"[SPS_TV_C_REPRODUCTOR_CATALOGO_ASIGNADO]";
        public const string CONSULTAREPRODUCTORES = @"[SPS_TV_C_REPRODUCTOR_All]";
        public const string CONSULTAREPRODUCTORESESTATUS = @"[SPI_TV_D_CANAL]";
        public const string CONSULTAREPRODUCTORESGRUPO = @"[SPS_TV_R_GRUPOS_REPRODUCTORES_ID_GRUPO]";
        public const string CONSULTAREPRODUCTORTEMPLATE = @"
        	SELECT r.*
,(SELECT ID_GRUPO 
	     FROM TV_R_GRUPO_REPRODUCTOR
		 WHERE ID_REPRODUCTOR = r.ID_REPRODUCTOR
		)ID_GRUPO
		,tr.*, t.*
	   
	FROM
	    TV_C_REPRODUCTOR r
	    LEFT JOIN TV_R_TEMPLATE_REPRODUCTOR tr
	    ON r.ID_REPRODUCTOR = tr.ID_REPRODUCTOR
	    LEFT JOIN TV_D_TEMPLATES t
	    ON tr.ID_TEMPLATE = t.ID_TEMPLATE 
	    WHERE r.ID_REPRODUCTOR = @ID_REPRODUCTOR 
        ";
        public const string CONSULTAREPRODUCTORTEMPLATEALL = @"
	SELECT r.*, tr.*, t.* FROM 
	TV_C_REPRODUCTOR r
	LEFT JOIN TV_R_TEMPLATE_REPRODUCTOR tr
	ON r.ID_REPRODUCTOR = tr.ID_REPRODUCTOR
	LEFT JOIN TV_D_TEMPLATES t
	ON tr.ID_TEMPLATE = t.ID_TEMPLATE 
                      WHERE(
                        r.DESCRIPCION LIKE CASE WHEN @Busqueda = '0' THEN r.DESCRIPCION ELSE '%' + @Busqueda +'%' END)
                      ORDER BY r.ID_REPRODUCTOR DESC
	OFFSET ((@Pagina-1) * @RegistrosPorPagina) ROWS
                      FETCH NEXT @RegistrosPorPagina ROWS ONLY 
        ";
    public static string ACTULIZARELOJ = @"UPDATE TV_C_REPRODUCTOR SET RELOJ = @RELOJ, USUARIO = @USUARIO WHERE ID_REPRODUCTOR = @ ID_REPRODUCTOR";

    public static string CONSULTAREPRODUCTORIP = @"SELECT * FROM TV_C_REPRODUCTOR WHERE IP_CLIENTE = @IP_CLIENTE";

    public static string CONSULTAREPRODUCTORMAC = @"SELECT * FROM TV_C_REPRODUCTOR WHERE DIRECCION_MAC = @DIRECCION_MAC";
  }
}
